[package]
name = "seguro_parametrico_meta"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
multiversx-sc-meta = "0.57.1"

[dependencies.seguro_parametrico_sc]
path = ".."
package = "seguro_parametrico_sc"
