[package]
name = "seguro_parametrico_meta"
version = "0.1.0"
edition = "2021"

[dependencies]
multiversx-sc-meta = "0.57.1"
multiversx-sc-meta-lib = "0.57.1" 

[dependencies.seguro_parametrico_sc]
path = "../seguro_parametrico_sc"
package = "seguro_parametrico_sc"
