// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    seguro_parametrico
    (
        init => init
        upgrade => upgrade
        registerPolicy => register_policy
        receber_fundos => receber_fundos
        triggerPayment => trigger_payment
        cancelarApolice => cancelar_apolice
        reativarApolice => reativar_apolice
        getPolicy => get_policy
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
